version: "3"

x-database: &postgres-credentials
  POSTGRES_USER: flatbot
  POSTGRES_PASSWORD: password
  POSTGRES_DB: flatbot
  POSTGRES_HOST: postgres

services:
  frontend:
    container_name: flatbot_frontend
    build: ./frontend
    command: npm run serve
    environment:
      API_URL: http://backend:4000/api
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/data
      - /data/node_modules
    

  backend:
    container_name: flatbot_backend
    build: ./backend
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      SECRET: '1r3jTQUSuKOQEUuT2eiusYpKLLde4kdA'
      <<: *postgres-credentials
    ports:
      - 4000:4000
    volumes:
      - ./backend:/data
      - /data/node_modules
    depends_on: 
      - postgres
  
  # SQL Shell:
  # docker-compose exec postgres psql -U admin -d avement 
  postgres:
    container_name: flatbot_postgres
    image: postgres:13
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      <<: *postgres-credentials
    ports:
      - 5432:5432
    volumes:
      - flatbot_postgres_volume:/var/lib/postgresql/data

volumes:
  flatbot_postgres_volume:
